# Generated by Django 4.0.5 on 2022-06-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_description_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='Cantidad',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='Precio',
        ),
    ]
