# Generated by Django 4.0.5 on 2022-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Marca',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
