# Generated by Django 4.0.5 on 2022-06-13 20:50

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=100)),
                ('Inicio_laboral', models.CharField(max_length=100)),
                ('Sueldo_mensual', models.FloatField(max_length=50)),
                ('Cuenta_corriente', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleado', models.CharField(max_length=50)),
                ('Sueldo', models.FloatField()),
                ('Comisiones', models.FloatField(null=multiprocessing.sharedctypes.Value)),
                ('Mes', models.CharField(max_length=50)),
                ('Año', models.IntegerField()),
            ],
        ),
    ]
