# Generated by Django 4.0.5 on 2022-06-13 21:20

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='Total',
            field=models.FloatField(null=multiprocessing.sharedctypes.Value),
            preserve_default=multiprocessing.sharedctypes.Value,
        ),
    ]
