# Generated by Django 4.0.5 on 2022-06-13 15:41

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='Fecha_de_entrega',
            field=models.DateTimeField(null=multiprocessing.sharedctypes.Value),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='Fecha_de_pedido',
            field=models.DateTimeField(),
        ),
    ]
