# Generated by Django 4.0.5 on 2022-06-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_orderproducts_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='Debe',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='Haber',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='Productos',
        ),
    ]
