# Generated by Django 4.0.5 on 2022-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_remove_suppliers_debe_remove_suppliers_haber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='Fecha_de_entrega',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='Fecha_de_pedido',
            field=models.CharField(max_length=8),
        ),
    ]
