# Generated by Django 4.0.5 on 2022-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_orderproducts_fecha_de_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='Telefono_de_contacto',
            field=models.IntegerField(null=True),
        ),
    ]
