# Generated by Django 4.0.5 on 2022-07-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_suppliers_telefono_de_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='Telefono_de_contacto',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
