# Generated by Django 4.0.5 on 2022-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_suppliers_telefono_de_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='Lista_de_productos',
            field=models.TextField(max_length=10000),
        ),
    ]
