# Generated by Django 4.0.5 on 2022-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_orderproducts_lista_de_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='Telefono_de_contacto',
            field=models.IntegerField(null=True),
        ),
    ]
