# Generated by Django 4.0.5 on 2022-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_cliente', models.CharField(max_length=50)),
                ('Nombre_del_local', models.CharField(max_length=50)),
                ('Localidad', models.CharField(max_length=50)),
                ('Direccion_del_local', models.CharField(max_length=50)),
                ('Cuenta_corriente', models.FloatField()),
            ],
        ),
    ]
